-- 주의: 이 SQL은 기존 게임 데이터를 전부 삭제합니다.
-- Supabase Dashboard > SQL Editor에서 전체를 한 번에 실행하세요.

begin;

-- 기존 테이블 삭제
-- 외래 키 관계를 고려해 기록 테이블부터 삭제합니다.
drop table if exists public.team_hint_views cascade;
drop table if exists public.investments cascade;
drop table if exists public.asset_prices cascade;
drop table if exists public.hints cascade;
drop table if exists public.assets cascade;
drop table if exists public.rounds cascade;
drop table if exists public.teams cascade;

-- 팀별 현재 자금만 실시간으로 관리합니다.
create table public.teams (
  id text primary key,
  slug text not null unique,
  name text not null,
  cash bigint not null default 1000000 check (cash >= 0)
);

-- 라운드의 열림/결과 공개 상태를 관리합니다.
-- 연도 정보는 코드에도 고정되어 있지만, 관리 편의를 위해 함께 저장합니다.
create table public.rounds (
  id text primary key,
  round_number integer not null unique check (round_number between 1 and 5),
  start_year integer not null,
  end_year integer not null,
  is_open boolean not null default false,
  is_result_open boolean not null default false
);

-- 산업 정보와 가격은 코드에 저장하므로 asset_id는 일반 문자열입니다.
create table public.investments (
  id bigint generated by default as identity primary key,
  team_id text not null references public.teams(id) on delete cascade,
  round_id text not null references public.rounds(id) on delete cascade,
  asset_id text not null,
  amount bigint not null check (amount >= 0),
  created_at timestamptz not null default now(),
  unique (team_id, round_id, asset_id)
);

-- 힌트 내용은 코드에 저장하고, 어떤 조가 무엇을 봤는지만 기록합니다.
create table public.team_hint_views (
  id bigint generated by default as identity primary key,
  team_id text not null references public.teams(id) on delete cascade,
  round_id text not null references public.rounds(id) on delete cascade,
  hint_id text not null,
  deducted_amount bigint not null check (deducted_amount >= 0),
  created_at timestamptz not null default now(),
  unique (team_id, round_id)
);

create index investments_team_round_idx
  on public.investments(team_id, round_id);

create index investments_round_idx
  on public.investments(round_id);

create index team_hint_views_team_round_idx
  on public.team_hint_views(team_id, round_id);

-- 8개 팀 초기 데이터
insert into public.teams (id, slug, name, cash) values
  ('team-1', 'team-1', '1조', 1000000),
  ('team-2', 'team-2', '2조', 1000000),
  ('team-3', 'team-3', '3조', 1000000),
  ('team-4', 'team-4', '4조', 1000000),
  ('team-5', 'team-5', '5조', 1000000),
  ('team-6', 'team-6', '6조', 1000000),
  ('team-7', 'team-7', '7조', 1000000),
  ('team-8', 'team-8', '8조', 1000000);

-- 5개 라운드 초기 데이터
insert into public.rounds (
  id,
  round_number,
  start_year,
  end_year,
  is_open,
  is_result_open
) values
  ('round-1', 1, 2015, 2017, false, false),
  ('round-2', 2, 2017, 2019, false, false),
  ('round-3', 3, 2019, 2021, false, false),
  ('round-4', 4, 2021, 2023, false, false),
  ('round-5', 5, 2023, 2025, false, false);

-- 현재 사이트는 별도 로그인 없이 anon key로 접근하므로 RLS를 끕니다.
-- 나누미만 주소에 접근한다는 전제의 간단한 수업용 설정입니다.
alter table public.teams disable row level security;
alter table public.rounds disable row level security;
alter table public.investments disable row level security;
alter table public.team_hint_views disable row level security;

-- anon/authenticated 역할에 필요한 권한 부여
grant select, insert, update, delete on public.teams to anon, authenticated;
grant select, insert, update, delete on public.rounds to anon, authenticated;
grant select, insert, update, delete on public.investments to anon, authenticated;
grant select, insert, update, delete on public.team_hint_views to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

commit;
